### ISSUE TITLE
The "Settings" table is mostly "undefined" / "N/A" sinec February 

### ISSUE THREAD

**Issue by foundryspatial-duncan** [puppeteer/pptr.dev#20]
If you click on the version number in the page header, a table comes up with the version / date / Chromium version. Since v2.1.1 in February, most (but not all) of the Chromium versions are listed as "undefined"
There's also an item at the top of the table right now that says "main - N/A - N/A"

**Comment by theDavidBarton** [comment]
(1) The `undefined` values indeed are bugs: once they are results of a not standardized release note process for Chromium version rolling (see below), and a lack of error handling on pptr.dev site. The cause is:
pptr.dev uses the following regex to parse the versions:
```javascript
const match = release.releaseNotes.match(/Chromium\s+(\d+\.\d+.\d+.\d+)\s*\((r\d{6})\)/i);
```
[(_source:_ src/pptr/PPTRProduct.js#L102)](https://github.com/puppeteer/pptr.dev/blob/master/src/pptr/PPTRProduct.js#L102)

The format of the Chromium version rolls has changed in the release notes lately:

While the regex matches: ["Chromium 86.0.4240.0 (r800071)"](https://github.com/puppeteer/puppeteer/releases/tag/v5.3.0) (v5.3.0)   
But it won't match: ["chromium: roll Chromium to r848005"](https://github.com/puppeteer/puppeteer/releases/tag/v7.0.0) (v7.0.0)  

It was intentional back then that it sometimes work sometimes not (there is even a [historical `else if` condition](https://github.com/puppeteer/pptr.dev/blob/master/src/pptr/PPTRProduct.js#L76) for such cases), anyway it would be correct to show `N/A` (not available) instead of `undefined`.

I will create a pull request to fix this and also raise a suggestion for the core team to include the full Chromium version in future releases (that could be in the [CONTRIBUTING.md's Rolling new Chromium version](https://github.com/puppeteer/puppeteer/blob/main/CONTRIBUTING.md#rolling-new-chromium-version) section).

(2) The item on top is by purpose showing `N/A`. That is the documentation on the `main` (previously `master`) branch, which doesn't have an exact release date, or a specific Chromium version. That is the all-time state of the `main` branch.
